feat: change shebang to use env

diff --git a/gh-erkin b/gh-erkin
--- a/gh-erkin
+++ b/gh-erkin
@@ -1,5 +1,10 @@
-#!/bin/bash
-set -e
+#!/usr/bin/env bash
+
+# Fail on unset variables and command errors
+set -ue -o pipefail
+
+# Prevent commands misbehaving due to locale differences
+export LC_ALL=C
 
 cat <<'EOF'
                                                                                 
